### ISSUE TITLE
[scaffolding-infra-chef] Allow injecting SSL certs for `chef` commands

### ISSUE THREAD

**Issue by jerryaldrichiii** [chef/effortless#111] opened 2019-07-29 19:46 UTC
For example, allowing the use of a custom SSL cert file for fetching from an on prem Artifactory.

**Comment by echohack** [comment] 2019-07-29 20:41
@jerryaldrichiii I think this could be a great feature. Can you provide an error log that you're receiving? That way we can create a negative test case for this, and then make it pass as we develop this feature in the future.

**Comment by echohack** [comment] 2019-07-29 21:34
This is a dupe of #104

**Closed by echohack** 2019-07-29 21:34 UTC
